# 1)Importing numpy as np and printing the version number

In [245]:
import numpy as np
np.__version__

'1.19.4'

# 2) Creating 1d array

In [225]:
arr = np.arange(10)
arr

array([0, 1, ..., 8, 9])

# 3) Creating 3*3 Boolean Array of all True's

In [168]:
bol_arr = arr < 10
bol_arr = np.array(bol_arr[:9].reshape(3,3))
print(bol_arr)

bol_arr1 = np.repeat(True,9).reshape(3,3)
bol_arr1

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4)Replacing all odd numbers in arr with -1

In [169]:
odd_arr = np.where(arr%2 != 0,-1,arr)
odd_arr

array([ 0, -1, ...,  8, -1])

# 5) Extracting all odd numbers from 1d array

In [170]:
odd_arr1 = np.where(arr%2 != 0)
odd_arr1

(array([1, 3, 5, 7, 9], dtype=int64),)

# 6) Replacing all odd numbers in arr with -1 without changing original arr

In [199]:
arr = np.arange(10)
arr1 = np.where(arr % 2 != 0, -1, arr)
print(arr1)

[ 0 -1 ...  8 -1]


# 7) Reshaping arr to 2d array shape

In [172]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, ..., 3, 4],
       [5, 6, ..., 8, 9]])

# 8) Stacking two arrays vertically

In [173]:
arr1 = np.arange(10,20).reshape(2,5)
arr = np.arange(10).reshape(2,5)
arr2 = np.vstack((arr,arr1))
arr2

array([[ 0,  1, ...,  3,  4],
       [ 5,  6, ...,  8,  9],
       [10, 11, ..., 13, 14],
       [15, 16, ..., 18, 19]])

# 9) Stacking two arrays horizontally

In [174]:
arr1 = np.arange(10,20).reshape(2,5)
arr = np.arange(10).reshape(2,5)
arr2 = np.hstack((arr,arr1))
arr2

array([[ 0,  1, ..., 13, 14],
       [ 5,  6, ..., 18, 19]])

# 10) Generating custom array without hardcoding

In [175]:
a = np.array([1,2,3])
a = np.hstack([np.repeat(a, 3), np.tile(a, 3)])
a

array([1, 1, ..., 2, 3])

# 11) Extracting common items in two arrays

In [176]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

# 12) Removing items from a those exist in b

In [177]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

# 13) Getting the positions where elements of a and b match

In [178]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
c

(array([1, 3, 5, 7], dtype=int64),)

# 14) Getting all items between 5 and 10 from a

In [204]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
b =  a[(a>=5) & (a<=10)]
b

array([ 6,  9, 10])

# 15) Converting the function maxx that works on two scalars, to work on two              arrays 

In [216]:
def pair_max(x, y):
    z = []
    #Get the maximum of two items
    for i,j in enumerate(x):
        if j >= y[i]:
            z.append(j)
        else:
            z.append(y[i])
    return np.array(z,dtype=float)
            
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
c = pair_max(a,b)
print(c,type(c))

#or

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)

[6. 7. ... 7. 5.] <class 'numpy.ndarray'>


array([6., 7., ..., 7., 5.])

# 16) Swapping columns 1 and 2 in the array arr.

In [181]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr = arr[:, [1, 0, 2]]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 17)Swapping rows 1 and 2 in the array arr 

In [182]:
arr = np.arange(9).reshape(3,3)
arr = arr[[1,0,2],:]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18)Reversing the rows of a 2D array arr

In [228]:
arr = np.arange(9).reshape(3,3)
arr = arr[::-1]
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 19)Reversing the columns of a 2D array arr

In [184]:
arr = np.arange(9).reshape(3,3)
arr = arr[:,::-1]
arr

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 20) Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [185]:
arr = np.arange(9).reshape(3,3)
r_arr = np.random.uniform(5,10,size=(5,3))
r_arr

array([[5.03, 6.54, 9.75],
       [5.63, 5.39, 6.56],
       ...,
       [9.6 , 6.49, 7.84],
       [5.89, 7.66, 8.23]])

# 21) Print or show only 3 decimal places of the numpy array rand_arr

In [250]:
rand_arr = np.random.uniform(10,size=(5,3))
print(rand_arr)
np.set_printoptions(precision=3)
rand_arr

[[2.839  9.8627 4.6104]
 [4.5658 9.0537 6.5625]
 ...
 [9.4605 1.9851 4.8079]
 [3.3177 4.3283 4.7634]]


array([[2.839, 9.863, 4.61 ],
       [4.566, 9.054, 6.563],
       ...,
       [9.461, 1.985, 4.808],
       [3.318, 4.328, 4.763]])

# 22) Pretty printing rand_arr by suppressing the scientific notation (like 1e10)

In [251]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)  
rand_arr

array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

# 23) Limiting the number of items printed in python numpy array a to a maximum of 6 elements

In [253]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1, ..., 13, 14])

# 24) Printing the full numpy array a without truncating

In [98]:
from sys import maxsize
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 25) Importing the iris dataset keeping the text intact

In [255]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object', names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'))
iris[:3]

array([(b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'),
       (b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'),
       (b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa')],
      dtype=[('sepallength', 'O'), ('sepalwidth', 'O'), ('petallength', 'O'), ('petalwidth', 'O'), ('species', 'O')])

# 26) Extracting the text column species from the 1D iris imported in previous question

In [257]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
species = np.array([row[4] for row in iris_1d])
species[:5]

C:\Program Files\Anaconda\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

# 27) Converting the 1D iris to 2D array iris_2d by omitting the species text field

In [101]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

C:\Program Files\Anaconda\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

# 28) Finding the mean, median, standard deviation of iris's sepallength (1st column)

In [263]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mean, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mean, med, sd,sep="\n")

5.843333333333334
5.8
0.8253012917851409


# 29) Creating a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [268]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0])
maxlen, minlen = sepallength.max(), sepallength.min()
norm_sepal = (sepallength - minlen)/(maxlen - minlen)
norm_sepal

array([0.222, 0.167, ..., 0.528, 0.444])

# 30) Calculating the softmax score of sepallength

In [262]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength = np.array([float(row[0]) for row in iris])

def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.002 0.002 ... 0.007 0.005]


# 31) Finding the 5th and 95th percentile of iris's sepallength

In [105]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, q=[5, 95])

array([4.6 , 7.25])

# 32) Inserting np.nan values at 20 random positions in iris_2d dataset

In [106]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Print first 10 rows
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


# 33)  Finding the number and position of missing values in iris_2d's sepallength (1st column)

In [107]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 5
Position of missing values: 
 (array([ 38,  80, 106, 113, 121], dtype=int64),)


# 34) Filtering the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [108]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

# 35) Selecting the rows of iris_2d that does not have any nan value

In [271]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       ...,
       [4.6, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

# 36) Finding the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

In [110]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution 1
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

# Solution 2
from scipy.stats.stats import pearsonr  
corr, p_value = pearsonr(iris[:, 0], iris[:, 2])
print(corr)

0.8717541573048713


# 37) Finding out if iris_2d has any missing values

In [111]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()

False

# 38)Replacing all occurrences of nan with 0 in numpy array

In [272]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0. ],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

# 39) Finding the unique values and the count of unique values in iris's species

In [113]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])

# Get the unique values and the counts
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

<h2> 40)Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:</h2>

<h3>
    <ul>
        <li>Less than 3 --> 'small'</li>
        <li>3-5 --> 'medium'</li>
        <li>'>=5 --> 'large'</li>
    </ul>
</h3>

In [114]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]

['small', 'small', 'small', 'small']

# 41)Creating a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [115]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

# Add the new column
out = np.hstack([iris_2d, volume])

# View
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

# 42)Randomly sample iris's species such that setose is twice the number of versicolor and virginica

In [116]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species column
species = iris[:, 4]

# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])

# Approach 2: Probablistic Sampling (preferred)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36], dtype=int64))


# 43) What is the value of second longest petallength of species setosa

In [117]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species and petal length columns
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

# Get the second last value
np.unique(np.sort(petal_len_setosa))[-2]

1.7

# 44)Sorting the iris dataset based on sepallength column.

In [274]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' ... b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' ... b'0.2' b'Iris-setosa']
 ...
 [b'4.9' b'3.1' ... b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' ... b'0.1' b'Iris-setosa']]


# 45)Finding the most frequent value of petal length (3rd column) in iris dataset.

In [275]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


# 46) Finding the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

In [276]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50], dtype=int64)

# 47)From the array a, replacing all values greater than 30 to 30 and less than 10 to 10.

In [277]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

np.clip(a, a_min=10, a_max=30)

print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.63 14.64 ... 30.   14.43]


# 48)Getting the positions of top 5 maximum values in a given array a.

In [278]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
#Solution 1:
print(a.argsort())
#> [18 7 3 10 15]

# Solution 2:
np.argpartition(-a, 5)[:5]
#> [15 10  3  7 18]

# Below methods will get you the values.
# Method 1:
a[a.argsort()][-5:]

# Method 2:
np.sort(a)[-5:]

# Method 3:
np.partition(a, kth=-5)[-5:]

# Method 4:
a[np.argpartition(-a, 5)][:5]

[ 4 13 ... 10 15]


array([48.95, 44.67, 42.39, 41.47, 41.  ])

# 49) Convert array_of_arrays into a flat linear 1d array.

In [123]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

# Solution 1
arr_2d = np.array([a for arr in array_of_arrays for a in arr])

# Solution 2:
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


C:\Program Files\Anaconda\lib\site-packages\ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


# 50)Computing the one-hot encodings (dummy binary variables for each unique value in the array)

In [285]:
# Input:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])

# Solution:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out
print(one_hot_encodings(arr))

# Method 2:
(arr[:, None] == np.unique(arr)).view(np.int8)

[[0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]]


array([[0, 1, 0],
       [0, 0, 1],
       ...,
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

# 51)Creating row numbers grouped by a categorical variable. Use the following sample from iris species as input.

In [125]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small)
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]
